server:
  port: ${PORT:8761}
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: https://${security.user.name}:${security.user.password}@registry-icu.herokuapp.com/eureka/

security:
  user:
    name: user
    password: ${REGISTRY_SERVER_PASSWORD:password}