server:
  port: ${PORT:8761}
eureka:
  instance:
    hostname: icu-registry.herokuapp.com
    non-secure-port: 80
    prefer-ip-address: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: https://${security.user.name}:${security.user.password}@icu-registry.herokuapp.com/eureka/

jasypt:
  encryptor:
    password: jazaradebuggers

spring:
  security:
    user:
      name: user
      password: ${REGISTRY_SERVER_PASSWORD:password}
